config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :cards
  namespace :admin do
    resources :users
    resources :announcements
    resources :notifications
    resources :services

    root to: "users#index"
  end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/card.rb
class Card < ApplicationRecord
  include CableReady::Broadcaster

  after_update do
    cable_ready["cards"].morph(
      selector: "#" + ActionView::RecordIdentifier.dom_id(self),
      html: ApplicationController.render(self)
    )
    cable_ready.broadcast
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def card_params
      params.require(:card).permit(:title, :description)
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_card.html.erb
<div id="<%= dom_id(card) %>" class="card card-body">
  <h4><%= card.title %></h4>
  <%= card.description %>
</div>

app/views/cards/_form.html.erb
<%= form_with(model: card, local: true) do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <% if card.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', card, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if card.persisted? %>
      <%= link_to "Cancel", card, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", cards_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Edit Card</h1>

<%= render 'form', card: @card %>

app/views/cards/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Cards</h1>
  </div>

  <div class="col-sm-6 text-right">
    <%= link_to new_card_path, class: 'btn btn-primary' do %>
      Add New Card
    <% end %>
  </div>
</div>

<%= render @cards %>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render 'form', card: @card %>

app/views/cards/show.html.erb
<div class="page-header">
  <%= link_to cards_path, class: 'btn btn-default' do %>
    All Cards
  <% end %>
  <%= link_to edit_card_path(@card), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1>Show card</h1>
</div>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @card.title %></dd>

  <dt>Description:</dt>
  <dd><%= @card.description %></dd>

</dl>